#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: acme-cart
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: acme-fitness-store
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  env:
  - name: CART_PORT
    value: "8080"
  - name: AUTH_URL
    value: #@ "https://authserver.{}".format(data.values.ingress.fqdn)
  - name: AUTH_MODE
    value: "1"
  - name: REDIS_HOST
    value: redis-master
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis
        key: redis-password
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
      apps.tanzu.vmware.com/pipeline: jenkins-pipeline
  - name: testing_pipeline_params
    value:
      job-name: maven_test
      secret-name: jenkins-tls
      job-params: "[{\"name\":\"GIT-URL\",\"value\":\"https://github.com/Eknathreddy09/tanzu-java-web-app\"},{\"name\":\"GIT-BRANCH\",\"value\":\"main\"}]"
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    subPath: apps/acme-cart
    git:
      url: https://github.com/explore-india-booth/acme-fitness-store
      ref:
        branch: main
